// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChoovd4l5oq0GBBZdUaiLQ-1jtaxw9Qds',
    appId: '1:854123972211:web:1b3453225997c46a958c06',
    messagingSenderId: '854123972211',
    projectId: 'wepay-817af',
    authDomain: 'wepay-817af.firebaseapp.com',
    storageBucket: 'wepay-817af.appspot.com',
    measurementId: 'G-QCSQ261BJG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD25a57-MCgyTyaNj0ixAk_ZwALK7GHWZI',
    appId: '1:854123972211:android:b50b70e58289cedf958c06',
    messagingSenderId: '854123972211',
    projectId: 'wepay-817af',
    storageBucket: 'wepay-817af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrEDN1v9MfAQA4KN8qwADtELDlth1G2wU',
    appId: '1:854123972211:ios:c6512a196c6f9ac1958c06',
    messagingSenderId: '854123972211',
    projectId: 'wepay-817af',
    storageBucket: 'wepay-817af.appspot.com',
    iosClientId: '854123972211-rubv9iu7170k29mvhbs7hp0csan3v5f1.apps.googleusercontent.com',
    iosBundleId: 'com.example.wePay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrEDN1v9MfAQA4KN8qwADtELDlth1G2wU',
    appId: '1:854123972211:ios:c6512a196c6f9ac1958c06',
    messagingSenderId: '854123972211',
    projectId: 'wepay-817af',
    storageBucket: 'wepay-817af.appspot.com',
    iosClientId: '854123972211-rubv9iu7170k29mvhbs7hp0csan3v5f1.apps.googleusercontent.com',
    iosBundleId: 'com.example.wePay',
  );
}
